name = "sistema-ax-festas"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[[pages_build_config]]
# Build command and output directory
build_command = "npm run pages:build"
destination_dir = ".vercel/output/static"

# Environment variables
[vars]
NODE_VERSION = "18"
